version: "3.8"

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: always