name: Merge Repositories

on: [repository_dispatch]

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    environment: actions

    steps:
    - name: Checkout fork
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Pull (Fast-Forward) upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: fga-eps-mds/2024.1-UnB-TV-Users
        upstream_branch: develop
        target_branch: develop
        git_pull_args: --ff-only
        github_token: ${{ secrets.API_GITHUB_TOKEN }}

    - name: Check for new commits
      if: steps.sync.outputs.has_new_commits
      run: echo "There were new commits."
