name: Merge Repositories

on: [repository_dispatch]

jobs:
  merge-repositories:
    runs-on: ubuntu-latest
    environment: actions

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Sync with upstream
        uses: tgymnich/fork-sync@v2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: develop
          base: develop
          merge_method: rebase
